// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menu-convert-to-markdown'
  | 'notification-error'
  | 'notification-failed'
  | 'notification-no-pdf'
  | 'notification-no-selection'
  | 'notification-single-only'
  | 'notification-success'
  | 'pref-help'
  | 'pref-mineru-api-key'
  | 'pref-mineru-api-url'
  | 'pref-mineru-description'
  | 'pref-mineru-title'
  | 'pref-title'
  | 'prefs-title'
  | 'progress-converting'
  | 'progress-done'
  | 'progress-failed'
  | 'progress-pending'
  | 'progress-processing'
  | 'progress-running'
  | 'progress-title'
  | 'startup-begin'
  | 'startup-finish';
