// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mineruApiKey": string;
      "mineruApiUrl": string;
      "aiProvider": string;
      "aiApiUrl": string;
      "aiApiKey": string;
      "aiModel": string;
      "aiAutoSummarize": boolean;
    };
  }
}
